# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmallUnit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmallUnit

  pod 'Mantis', '~> 1.4.8'

  target 'SmallUnitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmallUnitUITests' do
    # Pods for testing
  end

end
